// This file is part of MinIO Operator
// Copyright (c) 2024 MinIO, Inc.
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU Affero General Public License for more details.
//
// You should have received a copy of the GNU Affero General Public License
// along with this program.  If not, see <http://www.gnu.org/licenses/>.

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v2

import (
	miniominiov2 "github.com/lgcorzo/operator/pkg/apis/minio.min.io/v2"
	appsv1 "k8s.io/api/apps/v1"
	v1 "k8s.io/api/core/v1"
)

// TenantSpecApplyConfiguration represents a declarative configuration of the TenantSpec type for use
// with apply.
//
// TenantSpec (`spec`) defines the configuration of a MinIO Tenant object. +
//
// The following parameters are specific to the `minio.min.io/v2` MinIO CRD API `spec` definition added as part of the MinIO Operator v4.0.0. +
//
// For more complete documentation on this object, see the https://min.io/docs/minio/kubernetes/upstream/operations/installation.html[MinIO Kubernetes Documentation]. +
type TenantSpecApplyConfiguration struct {
	// *Required* +
	//
	// An array of objects describing each MinIO server pool deployed in the MinIO Tenant. Each pool consists of a set of MinIO server pods which "pool" their storage resources for supporting object storage and retrieval requests. Each server pool is independent of all others and supports horizontal scaling of available storage resources in the MinIO Tenant. +
	//
	// The MinIO Tenant `spec` *must have* at least *one* element in the `pools` array. +
	//
	// See the https://min.io/docs/minio/kubernetes/upstream/operations/install-deploy-manage/deploy-minio-tenant.html[MinIO Operator CRD] reference for the `pools` object for examples and more complete documentation.
	Pools []PoolApplyConfiguration `json:"pools,omitempty"`
	// *Optional* +
	//
	// The Docker image to use when deploying `minio` server pods. Defaults to {minio-image}. +
	Image *string `json:"image,omitempty"`
	// *Optional* +
	//
	// Specify the secret key to use for pulling images from a private Docker repository. +
	ImagePullSecret *v1.LocalObjectReference `json:"imagePullSecret,omitempty"`
	// *Optional* +
	//
	// Pod Management Policy for pod created by StatefulSet
	PodManagementPolicy *appsv1.PodManagementPolicyType `json:"podManagementPolicy,omitempty"`
	// *Optional* +
	//
	// If provided, the MinIO Operator adds the specified environment variables when deploying the Tenant resource.
	Env []v1.EnvVar `json:"env,omitempty"`
	// *Optional* +
	//
	// Enables TLS with SNI support on each MinIO pod in the tenant. If `externalCertSecret` is omitted *and* `requestAutoCert` is set to `false`, the MinIO Tenant deploys *without* TLS enabled. +
	//
	// Specify an array of https://kubernetes.io/docs/concepts/configuration/secret/[Kubernetes TLS secrets]. The MinIO Operator copies the specified certificates to every MinIO server pod in the tenant. When the MinIO pod/service responds to a TLS connection request, it uses SNI to select the certificate with matching `subjectAlternativeName`. +
	//
	// Each element in the `externalCertSecret` array is an object containing the following fields: +
	//
	// * - `name` - The name of the Kubernetes secret containing the TLS certificate. +
	//
	// * - `type` - Specify `kubernetes.io/tls` +
	//
	// See the https://min.io/docs/minio/kubernetes/upstream/operations/install-deploy-manage/deploy-minio-tenant.html#create-tenant-security-section[MinIO Operator CRD] reference for examples and more complete documentation on configuring TLS for MinIO Tenants.
	ExternalCertSecret []*miniominiov2.LocalCertificateReference `json:"externalCertSecret,omitempty"`
	// *Optional* +
	//
	// Allows MinIO server pods to verify client TLS certificates signed by a Certificate Authority not in the pod's trust store. +
	//
	// Specify an array of https://kubernetes.io/docs/concepts/configuration/secret/[Kubernetes TLS secrets]. The MinIO Operator copies the specified certificates to every MinIO server pod in the tenant. +
	//
	// Each element in the `externalCertSecret` array is an object containing the following fields: +
	//
	// * - `name` - The name of the Kubernetes secret containing the Certificate Authority. +
	//
	// * - `type` - Specify `kubernetes.io/tls`. +
	//
	// See the https://min.io/docs/minio/kubernetes/upstream/operations/install-deploy-manage/deploy-minio-tenant.html#create-tenant-security-section[MinIO Operator CRD] reference for examples and more complete documentation on configuring TLS for MinIO Tenants.
	ExternalCaCertSecret []*miniominiov2.LocalCertificateReference `json:"externalCaCertSecret,omitempty"`
	// *Optional* +
	//
	// Enables mTLS authentication between the MinIO Tenant pods and https://github.com/minio/kes[MinIO KES]. *Required* for enabling connectivity between the MinIO Tenant and MinIO KES. +
	//
	// Specify a https://kubernetes.io/docs/concepts/configuration/secret/[Kubernetes TLS secrets]. The MinIO Operator copies the specified certificate to every MinIO server pod in the tenant. The secret *must* contain the following fields: +
	//
	// * `name` - The name of the Kubernetes secret containing the TLS certificate. +
	//
	// * `type` - Specify `kubernetes.io/tls` +
	//
	// The specified certificate *must* correspond to an identity on the KES server. See the https://github.com/minio/kes/wiki/Configuration#policy-configuration[KES Wiki] for more information on KES identities. +
	//
	// If deploying KES with the MinIO Operator, include the hash of the certificate as part of the <<k8s-api-github-com-minio-operator-pkg-apis-minio-min-io-v2-kesconfig,`kes`>> object specification. +
	//
	// See the https://min.io/docs/minio/kubernetes/upstream/operations/install-deploy-manage/deploy-minio-tenant.html#create-tenant-security-section[MinIO Operator CRD] reference for examples and more complete documentation on configuring TLS for MinIO Tenants.
	ExternalClientCertSecret *LocalCertificateReferenceApplyConfiguration `json:"externalClientCertSecret,omitempty"`
	// *Optional* +
	//
	// Provide support for mounting additional client certificate into MinIO Tenant pods
	// Multiple client certificates will be mounted using the following folder structure: +
	//
	// * certs +
	//
	// * * client-0 +
	//
	// * * * client.crt +
	//
	// * * * client.key +
	//
	// * * client-1 +
	//
	// * * * client.crt +
	//
	// * * * client.key +
	//
	// * * * client-2 +
	//
	// * * client.crt +
	//
	// * * *  client.key +
	//
	// Specify a https://kubernetes.io/docs/concepts/configuration/secret/[Kubernetes TLS secrets]. The MinIO Operator copies the specified certificate to every MinIO server pod in the tenant that later can be referenced using environment variables. The secret *must* contain the following fields: +
	//
	// * `name` - The name of the Kubernetes secret containing the TLS certificate. +
	//
	// * `type` - Specify `kubernetes.io/tls` +
	ExternalClientCertSecrets []*miniominiov2.LocalCertificateReference `json:"externalClientCertSecrets,omitempty"`
	// *Optional* +
	//
	// Mount path for MinIO volume (PV). Defaults to `/export`
	Mountpath *string `json:"mountPath,omitempty"`
	// *Optional* +
	//
	// Subpath inside mount path. This is the directory where MinIO stores data. Default to `""“ (empty)
	Subpath *string `json:"subPath,omitempty"`
	// *Optional* +
	//
	// Enables using https://kubernetes.io/docs/tasks/tls/managing-tls-in-a-cluster/[Kubernetes-based TLS certificate generation] and signing for pods and services in the MinIO Tenant. +
	//
	// * Specify `true` to explicitly enable automatic certificate generate (Default). +
	//
	// * Specify `false` to disable automatic certificate generation. +
	//
	// If `requestAutoCert` is set to `false` *and* `externalCertSecret` is omitted, the MinIO Tenant deploys *without* TLS enabled.
	//
	// See the https://min.io/docs/minio/kubernetes/upstream/operations/install-deploy-manage/deploy-minio-tenant.html#create-tenant-security-section[MinIO Operator CRD] reference for examples and more complete documentation on configuring TLS for MinIO Tenants.
	RequestAutoCert *bool `json:"requestAutoCert,omitempty"`
	// CertExpiryAlertThreshold is the minimum number of days to expiry before an alert for an expiring certificate is fired.
	CertExpiryAlertThreshold *int32 `json:"certExpiryAlertThreshold,omitempty"`
	// Liveness Probe for container liveness. Container will be restarted if the probe fails.
	Liveness *v1.Probe `json:"liveness,omitempty"`
	// Readiness Probe for container readiness. Container will be removed from service endpoints if the probe fails.
	Readiness *v1.Probe `json:"readiness,omitempty"`
	// Startup Probe allows to configure a max grace period for a pod to start before getting traffic routed to it.
	Startup *v1.Probe `json:"startup,omitempty"`
	// Lifecycle hooks for container.
	Lifecycle *v1.Lifecycle `json:"lifecycle,omitempty"`
	// S3 related features can be disabled or enabled such as `bucketDNS` etc.
	Features *FeaturesApplyConfiguration `json:"features,omitempty"`
	// *Optional* +
	//
	// Enables setting the `CommonName`, `Organization`, and `dnsName` attributes for all TLS certificates automatically generated by the Operator. Configuring this object has no effect if `requestAutoCert` is `false`. +
	CertConfig *CertificateConfigApplyConfiguration `json:"certConfig,omitempty"`
	// *Optional* +
	//
	// Directs the MinIO Operator to deploy the https://github.com/minio/kes[MinIO Key Encryption Service] (KES) using the specified configuration. The MinIO KES supports performing server-side encryption of objects on the MiNIO Tenant. +
	KES *KESConfigApplyConfiguration `json:"kes,omitempty"`
	// *Optional* +
	//
	// Directs the MinIO Operator to use prometheus operator. +
	//
	// Tenant scrape configuration will be added to prometheus managed by the prometheus-operator.
	PrometheusOperator *bool `json:"prometheusOperator,omitempty"`
	// *Optional* +
	//
	// API end point(s) to scrape metrics from PrometheusOperatorScrapeMetricsPaths
	// If PrometheusOperator: true and PrometheusOperatorScrapeMetricsPaths is empty, will add `/minio/v2/metrics/cluster` to the list of paths to scrape as default like before.
	PrometheusOperatorScrapeMetricsPaths []string `json:"prometheusOperatorScrapeMetricsPaths,omitempty"`
	// *Optional* +
	//
	// The https://kubernetes.io/docs/tasks/configure-pod-container/configure-service-account/[Kubernetes Service Account] to use for running MinIO pods created as part of the Tenant. +
	ServiceAccountName *string `json:"serviceAccountName,omitempty"`
	// *Optional* +
	//
	// Indicates the Pod priority and therefore importance of a Pod relative to other Pods in the cluster.
	// This is applied to MinIO pods only. +
	//
	// Refer Kubernetes https://kubernetes.io/docs/concepts/configuration/pod-priority-preemption/#priorityclass[Priority Class documentation] for more complete documentation.
	PriorityClassName *string `json:"priorityClassName,omitempty"`
	// *Optional* +
	//
	// The pull policy for the MinIO Docker image. Specify one of the following: +
	//
	// * `Always` +
	//
	// * `Never` +
	//
	// * `IfNotPresent` (Default) +
	//
	// Refer Kubernetes documentation for details https://kubernetes.io/docs/concepts/containers/images#updating-images
	ImagePullPolicy *v1.PullPolicy `json:"imagePullPolicy,omitempty"`
	// *Optional* +
	//
	// A list of containers to run as sidecars along every MinIO Pod deployed in the tenant.
	SideCars *SideCarsApplyConfiguration `json:"sideCars,omitempty"`
	// *Optional* +
	//
	// Directs the Operator to expose the MinIO and/or Console services. +
	ExposeServices *ExposeServicesApplyConfiguration `json:"exposeServices,omitempty"`
	// *Optional* +
	//
	// Specify custom labels and annotations to append to the MinIO service and/or Console service.
	ServiceMetadata *ServiceMetadataApplyConfiguration `json:"serviceMetadata,omitempty"`
	// *Optional* +
	//
	// Specify custom labels and annotations to append to all pool statefulsets and pods.
	PoolsMetadata *PoolsMetadataApplyConfiguration `json:"poolsMetadata,omitempty"`
	// *Optional* +
	//
	// An array of https://kubernetes.io/docs/concepts/configuration/secret/[Kubernetes opaque secrets] to use for generating MinIO users during tenant provisioning. +
	//
	// Each element in the array is an object consisting of a key-value pair `name: <string>`, where the `<string>` references an opaque Kubernetes secret. +
	//
	// Each referenced Kubernetes secret must include the following fields: +
	//
	// * `CONSOLE_ACCESS_KEY` - The "Username" for the MinIO user +
	//
	// * `CONSOLE_SECRET_KEY` - The "Password" for the MinIO user +
	//
	// The Operator creates each user with the `consoleAdmin` policy by default. You can change the assigned policy after the Tenant starts. +
	Users []v1.LocalObjectReference `json:"users,omitempty"`
	// *Optional* +
	//
	// Create buckets when creating a new tenant. Skip if bucket with given name already exists
	Buckets []BucketApplyConfiguration `json:"buckets,omitempty"`
	// *Optional* +
	//
	// Enable JSON, Anonymous logging for MinIO tenants.
	Logging *LoggingApplyConfiguration `json:"logging,omitempty"`
	// *Optional* +
	//
	// Specify a secret that contains additional environment variable configurations to be used for the MinIO pools.
	// The secret is expected to have a key named config.env containing all exported environment variables for MinIO+
	Configuration *v1.LocalObjectReference `json:"configuration,omitempty"`
	// *Optional* +
	//
	// Add custom initContainers to StatefulSet
	InitContainers []v1.Container `json:"initContainers,omitempty"`
	// *Optional* +
	//
	// If provided, statefulset will add these volumes. You should set the rules for the corresponding volumes and volume mounts. We will not test this rule, k8s will show the result.
	AdditionalVolumes []v1.Volume `json:"additionalVolumes,omitempty"`
	// *Optional* +
	//
	// If provided, statefulset will add these volumes. You should set the rules for the corresponding volumes and volume mounts. We will not test this rule, k8s will show the result.
	AdditionalVolumeMounts []v1.VolumeMount `json:"additionalVolumeMounts,omitempty"`
}

// TenantSpecApplyConfiguration constructs a declarative configuration of the TenantSpec type for use with
// apply.
func TenantSpec() *TenantSpecApplyConfiguration {
	return &TenantSpecApplyConfiguration{}
}

// WithPools adds the given value to the Pools field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Pools field.
func (b *TenantSpecApplyConfiguration) WithPools(values ...*PoolApplyConfiguration) *TenantSpecApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithPools")
		}
		b.Pools = append(b.Pools, *values[i])
	}
	return b
}

// WithImage sets the Image field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Image field is set to the value of the last call.
func (b *TenantSpecApplyConfiguration) WithImage(value string) *TenantSpecApplyConfiguration {
	b.Image = &value
	return b
}

// WithImagePullSecret sets the ImagePullSecret field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ImagePullSecret field is set to the value of the last call.
func (b *TenantSpecApplyConfiguration) WithImagePullSecret(value v1.LocalObjectReference) *TenantSpecApplyConfiguration {
	b.ImagePullSecret = &value
	return b
}

// WithPodManagementPolicy sets the PodManagementPolicy field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the PodManagementPolicy field is set to the value of the last call.
func (b *TenantSpecApplyConfiguration) WithPodManagementPolicy(value appsv1.PodManagementPolicyType) *TenantSpecApplyConfiguration {
	b.PodManagementPolicy = &value
	return b
}

// WithEnv adds the given value to the Env field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Env field.
func (b *TenantSpecApplyConfiguration) WithEnv(values ...v1.EnvVar) *TenantSpecApplyConfiguration {
	for i := range values {
		b.Env = append(b.Env, values[i])
	}
	return b
}

// WithExternalCertSecret adds the given value to the ExternalCertSecret field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the ExternalCertSecret field.
func (b *TenantSpecApplyConfiguration) WithExternalCertSecret(values ...**miniominiov2.LocalCertificateReference) *TenantSpecApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithExternalCertSecret")
		}
		b.ExternalCertSecret = append(b.ExternalCertSecret, *values[i])
	}
	return b
}

// WithExternalCaCertSecret adds the given value to the ExternalCaCertSecret field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the ExternalCaCertSecret field.
func (b *TenantSpecApplyConfiguration) WithExternalCaCertSecret(values ...**miniominiov2.LocalCertificateReference) *TenantSpecApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithExternalCaCertSecret")
		}
		b.ExternalCaCertSecret = append(b.ExternalCaCertSecret, *values[i])
	}
	return b
}

// WithExternalClientCertSecret sets the ExternalClientCertSecret field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ExternalClientCertSecret field is set to the value of the last call.
func (b *TenantSpecApplyConfiguration) WithExternalClientCertSecret(value *LocalCertificateReferenceApplyConfiguration) *TenantSpecApplyConfiguration {
	b.ExternalClientCertSecret = value
	return b
}

// WithExternalClientCertSecrets adds the given value to the ExternalClientCertSecrets field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the ExternalClientCertSecrets field.
func (b *TenantSpecApplyConfiguration) WithExternalClientCertSecrets(values ...**miniominiov2.LocalCertificateReference) *TenantSpecApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithExternalClientCertSecrets")
		}
		b.ExternalClientCertSecrets = append(b.ExternalClientCertSecrets, *values[i])
	}
	return b
}

// WithMountpath sets the Mountpath field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Mountpath field is set to the value of the last call.
func (b *TenantSpecApplyConfiguration) WithMountpath(value string) *TenantSpecApplyConfiguration {
	b.Mountpath = &value
	return b
}

// WithSubpath sets the Subpath field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Subpath field is set to the value of the last call.
func (b *TenantSpecApplyConfiguration) WithSubpath(value string) *TenantSpecApplyConfiguration {
	b.Subpath = &value
	return b
}

// WithRequestAutoCert sets the RequestAutoCert field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the RequestAutoCert field is set to the value of the last call.
func (b *TenantSpecApplyConfiguration) WithRequestAutoCert(value bool) *TenantSpecApplyConfiguration {
	b.RequestAutoCert = &value
	return b
}

// WithCertExpiryAlertThreshold sets the CertExpiryAlertThreshold field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the CertExpiryAlertThreshold field is set to the value of the last call.
func (b *TenantSpecApplyConfiguration) WithCertExpiryAlertThreshold(value int32) *TenantSpecApplyConfiguration {
	b.CertExpiryAlertThreshold = &value
	return b
}

// WithLiveness sets the Liveness field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Liveness field is set to the value of the last call.
func (b *TenantSpecApplyConfiguration) WithLiveness(value v1.Probe) *TenantSpecApplyConfiguration {
	b.Liveness = &value
	return b
}

// WithReadiness sets the Readiness field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Readiness field is set to the value of the last call.
func (b *TenantSpecApplyConfiguration) WithReadiness(value v1.Probe) *TenantSpecApplyConfiguration {
	b.Readiness = &value
	return b
}

// WithStartup sets the Startup field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Startup field is set to the value of the last call.
func (b *TenantSpecApplyConfiguration) WithStartup(value v1.Probe) *TenantSpecApplyConfiguration {
	b.Startup = &value
	return b
}

// WithLifecycle sets the Lifecycle field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Lifecycle field is set to the value of the last call.
func (b *TenantSpecApplyConfiguration) WithLifecycle(value v1.Lifecycle) *TenantSpecApplyConfiguration {
	b.Lifecycle = &value
	return b
}

// WithFeatures sets the Features field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Features field is set to the value of the last call.
func (b *TenantSpecApplyConfiguration) WithFeatures(value *FeaturesApplyConfiguration) *TenantSpecApplyConfiguration {
	b.Features = value
	return b
}

// WithCertConfig sets the CertConfig field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the CertConfig field is set to the value of the last call.
func (b *TenantSpecApplyConfiguration) WithCertConfig(value *CertificateConfigApplyConfiguration) *TenantSpecApplyConfiguration {
	b.CertConfig = value
	return b
}

// WithKES sets the KES field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the KES field is set to the value of the last call.
func (b *TenantSpecApplyConfiguration) WithKES(value *KESConfigApplyConfiguration) *TenantSpecApplyConfiguration {
	b.KES = value
	return b
}

// WithPrometheusOperator sets the PrometheusOperator field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the PrometheusOperator field is set to the value of the last call.
func (b *TenantSpecApplyConfiguration) WithPrometheusOperator(value bool) *TenantSpecApplyConfiguration {
	b.PrometheusOperator = &value
	return b
}

// WithPrometheusOperatorScrapeMetricsPaths adds the given value to the PrometheusOperatorScrapeMetricsPaths field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the PrometheusOperatorScrapeMetricsPaths field.
func (b *TenantSpecApplyConfiguration) WithPrometheusOperatorScrapeMetricsPaths(values ...string) *TenantSpecApplyConfiguration {
	for i := range values {
		b.PrometheusOperatorScrapeMetricsPaths = append(b.PrometheusOperatorScrapeMetricsPaths, values[i])
	}
	return b
}

// WithServiceAccountName sets the ServiceAccountName field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ServiceAccountName field is set to the value of the last call.
func (b *TenantSpecApplyConfiguration) WithServiceAccountName(value string) *TenantSpecApplyConfiguration {
	b.ServiceAccountName = &value
	return b
}

// WithPriorityClassName sets the PriorityClassName field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the PriorityClassName field is set to the value of the last call.
func (b *TenantSpecApplyConfiguration) WithPriorityClassName(value string) *TenantSpecApplyConfiguration {
	b.PriorityClassName = &value
	return b
}

// WithImagePullPolicy sets the ImagePullPolicy field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ImagePullPolicy field is set to the value of the last call.
func (b *TenantSpecApplyConfiguration) WithImagePullPolicy(value v1.PullPolicy) *TenantSpecApplyConfiguration {
	b.ImagePullPolicy = &value
	return b
}

// WithSideCars sets the SideCars field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the SideCars field is set to the value of the last call.
func (b *TenantSpecApplyConfiguration) WithSideCars(value *SideCarsApplyConfiguration) *TenantSpecApplyConfiguration {
	b.SideCars = value
	return b
}

// WithExposeServices sets the ExposeServices field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ExposeServices field is set to the value of the last call.
func (b *TenantSpecApplyConfiguration) WithExposeServices(value *ExposeServicesApplyConfiguration) *TenantSpecApplyConfiguration {
	b.ExposeServices = value
	return b
}

// WithServiceMetadata sets the ServiceMetadata field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ServiceMetadata field is set to the value of the last call.
func (b *TenantSpecApplyConfiguration) WithServiceMetadata(value *ServiceMetadataApplyConfiguration) *TenantSpecApplyConfiguration {
	b.ServiceMetadata = value
	return b
}

// WithPoolsMetadata sets the PoolsMetadata field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the PoolsMetadata field is set to the value of the last call.
func (b *TenantSpecApplyConfiguration) WithPoolsMetadata(value *PoolsMetadataApplyConfiguration) *TenantSpecApplyConfiguration {
	b.PoolsMetadata = value
	return b
}

// WithUsers adds the given value to the Users field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Users field.
func (b *TenantSpecApplyConfiguration) WithUsers(values ...v1.LocalObjectReference) *TenantSpecApplyConfiguration {
	for i := range values {
		b.Users = append(b.Users, values[i])
	}
	return b
}

// WithBuckets adds the given value to the Buckets field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Buckets field.
func (b *TenantSpecApplyConfiguration) WithBuckets(values ...*BucketApplyConfiguration) *TenantSpecApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithBuckets")
		}
		b.Buckets = append(b.Buckets, *values[i])
	}
	return b
}

// WithLogging sets the Logging field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Logging field is set to the value of the last call.
func (b *TenantSpecApplyConfiguration) WithLogging(value *LoggingApplyConfiguration) *TenantSpecApplyConfiguration {
	b.Logging = value
	return b
}

// WithConfiguration sets the Configuration field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Configuration field is set to the value of the last call.
func (b *TenantSpecApplyConfiguration) WithConfiguration(value v1.LocalObjectReference) *TenantSpecApplyConfiguration {
	b.Configuration = &value
	return b
}

// WithInitContainers adds the given value to the InitContainers field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the InitContainers field.
func (b *TenantSpecApplyConfiguration) WithInitContainers(values ...v1.Container) *TenantSpecApplyConfiguration {
	for i := range values {
		b.InitContainers = append(b.InitContainers, values[i])
	}
	return b
}

// WithAdditionalVolumes adds the given value to the AdditionalVolumes field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the AdditionalVolumes field.
func (b *TenantSpecApplyConfiguration) WithAdditionalVolumes(values ...v1.Volume) *TenantSpecApplyConfiguration {
	for i := range values {
		b.AdditionalVolumes = append(b.AdditionalVolumes, values[i])
	}
	return b
}

// WithAdditionalVolumeMounts adds the given value to the AdditionalVolumeMounts field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the AdditionalVolumeMounts field.
func (b *TenantSpecApplyConfiguration) WithAdditionalVolumeMounts(values ...v1.VolumeMount) *TenantSpecApplyConfiguration {
	for i := range values {
		b.AdditionalVolumeMounts = append(b.AdditionalVolumeMounts, values[i])
	}
	return b
}
